version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: dna_testing_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_DATABASE: dna_testing_db
      MYSQL_USER: dna_user
      MYSQL_PASSWORD: "dna_password"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # - ./database/init:/docker-entrypoint-initdb.d  # Not needed - Spring Boot handles initialization
    networks:
      - dna_network

volumes:
  mysql_data:

networks:
  dna_network:
    driver: bridge